package rzk;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.4.7
 * 2022-12-13T23:19:12.866+01:00
 * Generated source version: 3.4.7
 *
 */
@WebService(targetNamespace = "http://webService.rzk/", name = "CountryInfRemote")
@XmlSeeAlso({ObjectFactory.class})
public interface CountryInfRemote {

    @WebMethod
    @RequestWrapper(localName = "getCode", targetNamespace = "http://webService.rzk/", className = "rzk.GetCode")
    @ResponseWrapper(localName = "getCodeResponse", targetNamespace = "http://webService.rzk/", className = "rzk.GetCodeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getCode(

        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
