package rzk;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.4.7
 * 2022-12-13T23:19:12.905+01:00
 * Generated source version: 3.4.7
 *
 */
@WebServiceClient(name = "CountryInfService",
                  wsdlLocation = "http://localhost:8080/CountryEJB/CountryInf?WSDL",
                  targetNamespace = "http://webService.rzk/")
public class CountryInfService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webService.rzk/", "CountryInfService");
    public final static QName CountryInfPort = new QName("http://webService.rzk/", "CountryInfPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/CountryEJB/CountryInf?WSDL");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CountryInfService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/CountryEJB/CountryInf?WSDL");
        }
        WSDL_LOCATION = url;
    }

    public CountryInfService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CountryInfService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountryInfService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CountryInfService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CountryInfService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CountryInfService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns CountryInfRemote
     */
    @WebEndpoint(name = "CountryInfPort")
    public CountryInfRemote getCountryInfPort() {
        return super.getPort(CountryInfPort, CountryInfRemote.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountryInfRemote
     */
    @WebEndpoint(name = "CountryInfPort")
    public CountryInfRemote getCountryInfPort(WebServiceFeature... features) {
        return super.getPort(CountryInfPort, CountryInfRemote.class, features);
    }

}
